### ISSUE TITLE
INFOGRAFIA-LENGUAJES DE PROGRAMACION 

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-carlos-chrs#1]
![lenguajes de programación para el desarrollo de contratos inteligentes](https://user-images.githubusercontent.com/79929498/165211960-50e69b61-28ed-48e3-a987-2480b71e9378.png)

**Comment by IsaHuerta23** [comment]
Partes de la infografía: 4 puntos. 
Coherencia y pertinencia: 4 puntos. 
Organización de la información: 4 puntos.
Diseño y composición de la infografía: 4 puntos.
Creatividad: 3 puntos.
Total: 19 puntos = Calificación: 19/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
